;========================
;        COLORS
;========================
[colors]
alert           = ${env:POLY_ALERT:#A54242}
background      = ${env:POLY_BG:#272728}
background-alt  = ${env:POLY_BG_ALT:#373B41}
disabled        = ${env:POLY_DISABLED:#707880}
foreground      = ${env:POLY_FG:#A6A0A0}
primary         = ${env:POLY_PRIMARY:#6BC72E}
secondary       = ${env:POLY_SECONDARY:#8ABEB7}
separator       = ${env:POLY_SEPARATOR:#413E3E}


;========================
;        SETTINGS
;========================
[settings]
pseudo-transparency = true
screenchange-reload = true


;========================
;          BAR
;========================
[bar/main]
background = ${colors.background}
border-color = #0F0F0F00
border-size = 2pt
cursor-click  = pointer
cursor-scroll = ns-resize
enable-ipc = true
font-0 = "Poppins:size=10;1"
font-1 = "Iosevka Nerd Font:size=10;1"
foreground = ${colors.foreground}
height = 20pt
line-size   = 2pt
module-margin = 1
modules-left   = xworkspaces sep memory sep cpu sep battery sep temperature sep pulseaudio sep 
modules-center = cava 
modules-right  = wlan sep bluetooth sep date sep power 
padding-left  = 6
padding-right = 6
radius = 10
width  = 100%


;========================
;      WORKSPACES
;========================
[module/xworkspaces]
label-active = %index%
label-active-background = ${colors.background}
label-active-foreground = ${colors.primary}
label-active-padding   = 2
label-active-underline  = ${colors.primary}
label-active-underline-size = 2pt
label-empty = %index%
label-empty-foreground = ${colors.foreground}
label-empty-padding   = 2
label-occupied = %index%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding  = 2
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.foreground}
label-urgent-padding   = 2
type = internal/xworkspaces


;========================
;        WINDOW
;========================
; [module/xwindow]
; label = %title:0:60:...%
; type = internal/xwindow


;========================
;        DATE
;========================
[module/date]
date     = %a, %d %b %Y, %H:%M
date-alt = %a %Y-%m-%d %H:%M:%S
interval = 1
label = %date%
label-foreground = ${colors.foreground}
tooltip-format = %date-alt%
type = internal/date


;========================
;          CAVA
;========================
[module/cava]
exec = $HOME/.config/polybar/cava.sh  
format = <label>
label = %{F#A6A0A0}%output%%{F-}   
tail = true
type = custom/script


;========================
;        AUDIO
;========================
[module/pulseaudio]
click-right = exec tilix -e wiremix
format-volume = <label-volume>
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
label-muted = muted
label-muted-foreground = ${colors.disabled}
label-volume  = %percentage%%
type = internal/pulseaudio


;========================
;        MEMORY
;========================
[module/memory]
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
interval = 2
label = %percentage_used:2%%
tooltip-format = %used%MB / %total%MB
type = internal/memory


;========================
;          CPU
;========================
[module/cpu]
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
interval = 2
label = %percentage:2%%
tooltip-format = %percentage%
type = internal/cpu


;========================
;       TEMPERATURE
;========================
[module/temperature]
format-prefix = "TMP "
format-prefix-foreground = ${colors.primary}
high-threshold = 80
interval = 2
label = %temperature:2%
label-high-foreground = ${colors.alert}
label-medium-foreground = ${colors.secondary}
medium-threshold = 60
tooltip-format = %temperature%°C
type = internal/temperature


;========================
;         BATTERY
;========================
[module/battery]
adapter = AC
battery = BAT0
format-charging = <label-charging>
format-charging-prefix = "BAT "
format-charging-prefix-foreground = ${colors.primary}
format-discharging = <label-discharging>
format-discharging-prefix = "BAT "
format-discharging-prefix-foreground = ${colors.primary}
format-full = <label-full>
format-full-prefix = "BAT "
format-full-prefix-foreground = ${colors.primary}
label-charging = %percentage%% %{F#FFFF00}⚡%{F-}
label-discharging = %percentage%% 
label-full = %percentage%% 
label-low = %percentage%%
label-low-foreground = ${colors.disabled}
low-at = 15
type = internal/battery


;========================
;        NETWORK BASE
;========================
[network-base]
format-connected = <label-connected>
format-disconnected = <label-disconnected>
interval = 5
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
type = internal/network


;========================
;        BLUETOOTH
;========================
[module/bluetooth]
click-left = ~/.config/polybar/toggle_bluetooth.sh
click-right = exec tilix -e bluetui
exec = ~/.config/polybar/bluetooth.sh
format = <label>
interval = 2
type = custom/script


;========================
;        WIFI
;========================
[module/wlan]
click-left = ~/.config/polybar/toggle_wifi.sh
click-right = exec tilix -e wifitui
exec = ~/.config/polybar/wifi.sh
format = <label>
interval = 2
type = custom/script


;========================
;       ETHERNET
;========================
[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%


;========================
;       SEPARATOR
;========================
[module/sep]
content = " |"
content-foreground = ${colors.separator}
content-padding = 1
type = custom/text


;========================
;          POWER
;========================
[module/power]
click-left = #power.open.0
expand-right = true
label-close = "⏻ "
label-close-foreground = #FFFFFF
label-close-padding = 2
label-open  = "⏻ "
label-open-foreground = #FFFFFF
label-open-padding = 2
label-separator = "   %{F#413E3E}|%{F-}   "
menu-0-0 = "%{F#54FB05}%{F-}%{O10}LO"
menu-0-0-exec = cinnamon-session-quit --logout --no-prompt
menu-0-1 = "%{F#FF5EF6}%{F-}%{O10}RBT"
menu-0-1-exec = systemctl reboot
menu-0-2 = "%{F#FE6145}%{F-}%{O10}PO"
menu-0-2-exec = systemctl poweroff
type = custom/menu


;========================
;      KEYBOARD
;========================
; [module/keyboard]
; format-prefix = "   KBD "
; format-prefix-foreground = ${colors.primary}
; label = %layout%
; label-foreground = ${colors.foreground}
; type = internal/xkeyboard
